version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      # Uncomment below and set the key to point to the proper file
      #- restore_cache:
          #name: Restore Yarn Package Json Cache
          #keys:            
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      # Uncomment below and set the key to point to the proper file
      #- save_cache:
          #name: Save Yarn Package Json Cache
          #key: 
          #paths:
            #- ~/.cache/yarn

workflows:
  cache-save-and-restore:
    jobs:
      - build